### ISSUE TITLE
Session Checklist

### ISSUE THREAD

**Issue by shwetal27** [shwetal27/open-innovation-lab#6]
- [ ] define the MVP and what I will be showcasing  
- [ ] research on designs/toolkits- narrow this down
- [ ] speak to organizations (google campus, o2 think big) to run sessions there- how would these help me roach the goals?
- [ ] narrow down on one challenge to begin with
- [ ] mockups for who I need to collaborate with/why- for next week
- [ ] create a video/MVP 
- [ ] reach out to users - and make sure they are part of the development community
- [ ] Create 2 week timeline to MozFest
- [ ] Minimum viable product
- [ ] Define the content of the MozFest session 
- [ ] Write  personas - who are your users? who are your contributors?
- [ ] Move Roadmap to github issue
- [ ] Make README.md more welcoming "  

2 Weeks Before      
- [ ] Plan with artist for the MozFest session
- [ ] Document to be given out to participants https://docs.google.com/document/d/1DjNz-Xd_qg5p8OAikCsZntB7zXlW21CfoRbvLppikM4/edit
- [ ] Session Vision https://docs.google.com/document/d/153PZwccu9iXXcixIYBexMDcbjBqe0vtEyDBa0sLZcIo/edit
- [ ] Comments & feedback from Project Mentorship calls Q: How will contributors interact with the website? Demo from Shwetal at MozFest of how to upload idea to website from github Need to make sure its possible to update website from github Reach out to open leaders community for help 
  Q: How will people use the website once it's updated?   github Use database to inspire hackathons for good Q: What's the unique value statement for this website? How is it different? More generaliseable, cross different problems and different specialties. Q: How will people find out about the website once its up and running- meetups, specific forums, using my own network Consider updating CONTRIBUTING to make sure people can spread the word easily 

1 Weeks Before      
- [ ] Fringe event being hosted 
- [ ] finalize the games. poems for the day 
- [ ] finalize the code on the site 
- [ ] gather all the material and goody bags for the participants  
- [ ] [Global] Blog FAQ about the event

The Day Before      
- [ ] print handouts  
- [ ] prepare goody bags
- [ ] prepare learning material 

The Morning of the Session      
- [ ] Set up signage  

Post network information
Session     
- [ ] Make introductions  
- [ ] Brief on the session  
- [ ] Mention the code of conduct  

At the End of the Session       
- [ ] Collect information for the live database 
- [ ] Mention follow-up sessions/ Hackathons  
- [ ] Mention Mozfest on day collab opportunity 

Follow Up  
    Thank You  
    Final email to attendees  
    Review post-session feedback  
    Blog Post  
    Future event planning
